name: Upload release binaries

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build Binaries
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goarch: [amd64, arm64]
        include:
          - goos: linux
            ext: ''
          - goos: darwin
            ext: ''
          - goos: windows
            ext: '.exe'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Get Tag Name
      id: tag

      run: echo "TAG_NAME=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT

    - name: Build Binary
      run: |
        TAG_NAME=$(echo "${{ steps.tag.outputs.TAG_NAME }}")
        GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o jorge-${TAG_NAME}-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.ext }} .

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: "jorge-*-*"
